### ISSUE TITLE
reproduce plugin

### ISSUE THREAD

**Issue by 1137305770** [depascaldc/NukkitX-Projects#1]
Hi author!
The LuckyBlocks-Nukkit plugin is great，could I reproduce the LuckyBlocks-Nukkit plugin to mcbbs? I marked you as the author in the MCBBS，Users download the LuckyBlocks-Nukkit plugin in your original Nukkitx forum

**Comment by depascaldc** [comment]
> Hi author!
> The LuckyBlocks-Nukkit plugin is great，could I reproduce the LuckyBlocks-Nukkit plugin to mcbbs? I marked you as the author in the MCBBS，Users download the LuckyBlocks-Nukkit plugin in your original Nukkitx forum

you can do that if you want yes.
